Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t3.xlarge
      ImageId: ami-06686d3646ac2170a  #EC2LaunchV2-Windows_Server 2016 
      KeyName: ServerKeys
      Tags:
        - Key: "Name"
          Value: "aszwin201601"
      SecurityGroups:
        - !Ref MySecurityGroup
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "AWSServerAccess"
      GroupName: "Server RDP Access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3389'
          ToPort: '3389'
          CidrIp: 172.31.0.0/16

                