Parameters:
  Environment:
    Description: Environment
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - dev
Mappings:
  RegionMap:
    us-east-1:
      dev: ami-0ff8a915
      prod: ami-0a584a
    us-west-1:
      dev: ami-0bdb828f
      prod: ami-066ee5fd
    eu-west-1:
      dev: ami-047bb416
      prod: ami-0a7c483d
Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:  !FindInMap [RegionMap, !Ref "AWS::Region", !Ref Environment]
      InstanceType: m1.small
